apiVersion: v1
kind: Pod
metadata:
  labels:
    run: redis-pod
    app: node-affinity
  name: redis-pod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: disktype
                operator: In
                values:
                  - ssd
                  - hdd
  containers:
    - image: redis
      name: redis-pod
      ports:
        - containerPort: 6379
