---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres-statefulset
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
  clusterIP: None
  selector:
    app: postgres-statefulset
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: postgres-statefulset
  name: postgres-statefulset
spec:
  serviceName: postgres-service
  minReadySeconds: 20
  replicas: 3
  selector:
    matchLabels:
      app: postgres-statefulset
  template:
    metadata:
      labels:
        app: postgres-statefulset
    spec:
      nodeName: node01
      terminationGracePeriodSeconds: 30
      volumes:
        - name: config
          configMap:
            name: postgres-config
      containers:
        - image: postgres
          name: postgres
          ports:
            - containerPort: 5432
              name: postgres
          command: ["/bin/bash", "-c"]
          args:
            - |
              set -e

              if [ ! -s "$PGDATA/PG_VERSION" ]; then

                if [[ "$HOSTNAME" == "postgres-statefulset-0" ]]; then
                  echo "Primary starting normally..."
                else
                  echo "Replica setup..."

                  until pg_isready -h postgres-statefulset-0.postgres-service; do
                    sleep 2
                  done

                  rm -rf $PGDATA/*
                  PGPASSWORD=$REPLICATION_PASSWORD pg_basebackup \
                    -h postgres-statefulset-0.postgres-service \
                    -D $PGDATA \
                    -U replicator \
                    -Fp -Xs -P -R
                fi
              fi

              exec docker-entrypoint.sh postgres
          envFrom:
          - secretRef:
              name: postgres-secret
          volumeMounts:
          - name: postgres-data
            mountPath: /var/lib/postgresql/data
          - name: config
            mountPath: /config
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi

  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: postgres-local-storage
      resources:
        requests:
          storage: 100Mi
---
