apiVersion: v1
kind: Pod
metadata:
  labels:
    run: redis-pod
    env: redis
  name: redis-pod
  namespace: default
spec:
  containers:
  - image: redis
    name: redis-pod
    ports:
    - containerPort: 6379
    nodeSelector:
      gpu: "true"
    tolerations:
    - key: "gpu"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always