apiVersion: v1
kind: Pod
metadata:
  labels:
    test: nginx-readiness
  name: nginx-readiness
spec:
  containers:
    - name: readiness
      image: nginx
      ports:
        - containerPorts: 80
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5
      resources:
        limits:
          cpu: 10m
          memory: 20Mi
        requests:
          cpu: 10m
          memory: 20Mi
