apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-pod-affinity
    app: pod-affinity
  name: nginx-pod-affinity
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: run
                operator: In
                values:
                  - redis-pod
          topologyKey: kubernetes.io/hostname
  containers:
    - image: nginx
      name: nginx-pod-affinity
      ports:
        - containerPort: 80
