apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-sidecar-pod
    env: prod
  name: nginx-sidecar-pod
  namespace: default
spec:
  containers:
  - name: busybox-init
    image: busybox
    command:
    - sh
    - -c
    args:
    - echo Hello world; sleep 5000
  - image: nginx
    name: nginx-pod
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always